export const teams = [
  {
    id: 'counterstrike',
    game: 'COUNTER-STRIKE',
    tag: 'OT',
    color: '#F0A500',
    region: 'NA',
    roster: [
      { name: 'UMAR', role: 'PLAYER', country: '🇺🇸', real: '@UmarQaiser2', twitter: 'https://x.com/UmarQaiser2' },
      { name: 'INTRAA', role: 'PLAYER', country: '🇺🇸', real: '@intrraa', twitter: 'https://x.com/intrraa' },
      { name: 'LEARSI', role: 'PLAYER', country: '🇺🇸', real: '@learsifarm', twitter: 'https://x.com/learsifarm' },
      { name: 'JASON', role: 'PLAYER', country: '🇺🇸', real: '@305jasonn', twitter: 'https://x.com/305jasonn' },
      { name: 'SACRIFICE', role: 'PLAYER', country: '🇺🇸', real: '@sacrificeCS', twitter: 'https://x.com/sacrificeCS' },
    ],
  },
  {
    id: 'deadlock',
    game: 'DEADLOCK',
    tag: 'OT',
    color: '#E8191A',
    region: 'NA',
    roster: [
      { name: 'SHEEP', role: 'PLAYER', country: '🇺🇸', real: '@SheepDL', twitter: 'https://x.com/SheepDL' },
      { name: 'VCIPHER', role: 'PLAYER', country: '🇺🇸', real: 'vCipher', twitter: '' },
      { name: 'E-IN', role: 'PLAYER', country: '🇺🇸', real: 'E-in', twitter: '' },
      { name: 'KIINGKOOOPA', role: 'PLAYER', country: '🇺🇸', real: '@KiiingKooopa', twitter: 'https://x.com/KiiingKooopa' },
      { name: 'DELINQUENT', role: 'PLAYER', country: '🇺🇸', real: '@delinquentFps', twitter: 'https://x.com/delinquentFps' },
      { name: 'MAXX', role: 'PLAYER', country: '🇺🇸', real: '@MaxxTF2', twitter: 'https://x.com/MaxxTF2' },
    ],
  },
  {
    id: 'r6academy',
    game: 'RAINBOW SIX ACADEMY',
    tag: 'OT',
    color: '#00D4FF',
    region: 'NA',
    roster: [
      { name: 'KEO', role: 'PLAYER', country: '🇺🇸', real: '@keo197', twitter: 'https://x.com/keo197' },
      { name: 'CAMO', role: 'PLAYER', country: '🇺🇸', real: '@Camo_R6', twitter: 'https://x.com/Camo_R6' },
      { name: 'FINAL', role: 'PLAYER', country: '🇺🇸', real: '@finalkiss_', twitter: 'https://x.com/finalkiss_' },
      { name: 'AJ', role: 'PLAYER', country: '🇺🇸', real: '@applejuice1007', twitter: 'https://x.com/applejuice1007' },
      { name: 'SWISZ', role: 'PLAYER', country: '🇺🇸', real: '@SwiszKVX', twitter: 'https://x.com/SwiszKVX' },
    ],
  },
  {
    id: 'r6female',
    game: 'RAINBOW SIX FEMALE',
    tag: 'OT',
    color: '#FF6FB5',
    region: 'NA',
    roster: [
      { name: 'NOTCIERRA', role: 'PLAYER', country: '🇺🇸', real: '@nottCierra', twitter: 'https://x.com/nottCierra' },
      { name: 'EMMAMUAH', role: 'PLAYER', country: '🇺🇸', real: '@emmamuahh', twitter: 'https://x.com/emmamuahh' },
      { name: 'AZZYRIAX', role: 'PLAYER', country: '🇺🇸', real: '@azzyriax', twitter: 'https://x.com/azzyriax' },
      { name: 'ERMIMPALA', role: 'PLAYER', country: '🇺🇸', real: '@ErmImpala', twitter: 'https://x.com/ErmImpala' },
      { name: 'ZEROWASGONE', role: 'PLAYER', country: '🇺🇸', real: '@zerowasgone', twitter: 'https://x.com/zerowasgone' },
      { name: 'ITSTHR1LL', role: 'SUB', country: '🇺🇸', real: '@itsTHR1LL', twitter: 'https://x.com/itsTHR1LL' },
    ],
  },
]

export const creators = [
  {
    id: 'kvstr',
    handle: 'KVSTR',
    real: 'KvstrSZN',
    platform: 'Twitch',
    followers: '2.2K',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 1,
    bio: "Overtake's Content Lead, shaping the org's creative direction while bringing consistent variety gaming content across Twitch and YouTube.",
    link: 'https://www.twitch.tv/KvstrSZN',
    photo: 'creator-kvstr.jpg',
    socials: { twitch: 'KvstrSZN', twitter: 'https://x.com/KvstrSZN', youtube: 'channel/UCykqzXBBbK_NF4QMBiwbp-A' },
  },
  {
    id: 'x19',
    handle: 'X19',
    real: 'X19_EH',
    platform: 'Twitch',
    followers: '800',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 3,
    bio: 'The gamer dad who never misses. X19 brings raw energy, unfiltered fun, and a community that feels like family — every stream, every time.',
    link: 'https://www.twitch.tv/x19_eh',
    photo: 'creatorr-x19.jpg',
    socials: { twitch: 'x19_eh', twitter: 'https://x.com/X19_EH', youtube: '' },
  },
  {
    id: 'luke',
    handle: 'LUKE',
    real: 'LukeFrywalker24',
    platform: 'Twitch',
    followers: '100',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 3,
    bio: 'Luke Frywalker is cooking up content one stream at a time. Fresh takes, good games, and a growing presence across Twitch and YouTube.',
    link: 'https://www.twitch.tv/luke_12345678932',
    photo: 'creator-Luke.jpg',
    socials: { twitch: 'luke_12345678932', twitter: 'https://x.com/LukeFrywalker24', youtube: '' },
  },
  {
    id: 'zendigo',
    handle: 'ZENDIGO',
    real: 'ZendigoPlayz',
    platform: 'Twitch',
    followers: '200',
    content: 'Speedrunning',
    country: '🇺🇸',
    specialty: 'SPEEDRUNS & RETRO',
    tier: 3,
    bio: 'Retro games, hidden gems, and speedruns that defy belief. Zendigo is on a mission to make the old feel new again — and the fast feel faster.',
    link: 'https://www.twitch.tv/zendigo_playz',
    photo: 'creator-Zendigo.jpg',
    socials: { twitch: 'zendigo_playz', twitter: 'https://x.com/ZendigoPlayz', youtube: '' },
  },
  {
    id: 'lordrogue',
    handle: 'LORDROGUE',
    real: 'LordRogue22',
    platform: 'Twitch',
    followers: '500',
    content: 'IRL & Apex',
    country: '🇺🇸',
    specialty: 'IRL & APEX',
    tier: 3,
    bio: 'Five years in the game and still going strong. Lord Rogue keeps it real — competitive Apex, genuine convos, and the foundation of his own rising empire, the Rogue Army.',
    link: 'https://www.twitch.tv/lordrogue22',
    photo: 'creator-Lordrogue.jpg',
    socials: { twitch: 'lordrogue22', twitter: 'https://x.com/LordRogue22', youtube: '' },
  },
  {
    id: 'midis',
    handle: 'MIDIS',
    real: 'midis1029',
    platform: 'TikTok',
    followers: '100',
    content: 'Call of Duty',
    country: '🇺🇸',
    specialty: 'CALL OF DUTY',
    tier: 3,
    bio: 'Grinding every day. Midis brings the CoD content nonstop — clips, gameplay, and the grind never stops.',
    link: 'https://www.tiktok.com/@midis1029',
    photo: 'creator-midis.jpg',
    socials: { twitch: '', twitter: '', youtube: '' },
  },
  {
    id: 'loki',
    handle: 'L0KI',
    real: 'L0ki_XG',
    platform: 'Twitch',
    followers: '1.5K',
    content: 'Call of Duty & Variety',
    country: '🇺🇸',
    specialty: 'COD & PODCAST HOST',
    tier: 2,
    bio: 'A Call of Duty creator who also dives into Gears of War, Diablo, Halo, and Hearthstone. Host of "Beyond the Console" — a podcast covering new games, Easter eggs, and honest opinions, plus interviews with streamers sharing their journeys and content.',
    link: 'https://www.twitch.tv/L0ki_XG',
    photo: 'creator-loki.png',
    socials: { twitch: 'L0ki_XG', twitter: 'https://x.com/ttv_loki', youtube: 'L0ki_XG' },
  },
  {
    id: 'nexus',
    handle: 'NEXUS',
    real: 'ttvtragedy',
    platform: 'Twitch',
    followers: '600',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 3,
    bio: 'Overtake\'s newest addition to the content division, bringing variety gaming content across Twitch and TikTok.',
    link: 'https://twitch.tv/ttvtragedy',
    photo: 'creator-nexus.jpg',
    socials: { twitch: 'ttvtragedy', twitter: '', youtube: '' },
  },
  {
    id: 'jg',
    handle: 'JG',
    real: 'JGKnown',
    platform: 'Twitch',
    followers: '950',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 2,
    bio: 'JG brings consistent variety gaming content to Twitch and TikTok, repping Overtake across platforms.',
    link: 'https://www.twitch.tv/jgknown',
    photo: 'creator-JG.jpg',
    socials: { twitch: 'jgknown', twitter: 'https://x.com/JGKnown', youtube: '' },
  },
  {
    id: 'nitromadness',
    handle: 'NITROMADNESS',
    real: 'nitromadnes',
    platform: 'Twitch',
    followers: '180',
    content: 'Call of Duty',
    country: '🇺🇸',
    specialty: 'CALL OF DUTY',
    tier: 3,
    bio: 'Car enthusiast turned gamer. Nitro brings CoD content to Twitch with a side of variety — unpredictable, unfiltered, and always in the mix.',
    link: 'https://www.twitch.tv/nitromadnes',
    photo: 'creator-nitromadness.png',
    socials: { twitch: 'nitromadnes', twitter: 'https://x.com/nitromadnes', youtube: '' },
  },
  {
    id: 'sherm',
    handle: 'SHERM',
    real: 'Sherm005',
    platform: 'YouTube',
    followers: '300',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 3,
    bio: 'Sherm brings competitive gaming content to YouTube and X, repping Overtake with consistent uploads and genuine gameplay.',
    link: 'https://www.youtube.com/channel/UCHn60qaorlwxIPJKkST2mlw',
    photo: 'creator-Sherm.jpg',
    socials: { twitch: '', twitter: 'https://x.com/Sherm005', youtube: 'channel/UCHn60qaorlwxIPJKkST2mlw' },
  },
  {
    id: 'ishh',
    handle: 'ISHH',
    real: 'vanIshh1of1',
    platform: 'Twitch',
    followers: '4.7K',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    tier: 2,
    bio: 'Ishh brings high-energy variety gaming content to Twitch, repping Overtake with a growing and engaged community.',
    link: 'https://www.twitch.tv/vanIshhFPS',
    photo: 'creator-Ishh.png',
    socials: { twitch: 'vanIshhFPS', twitter: 'https://x.com/vanIshh1of1', youtube: '' },
  },
]

export const partners = [
  {
    name: 'RepulseCo',
    category: 'Apparel',
    tier: 'Official',
    desc: 'The fear of being normal. RepulseCo is redefining the future of esports clothing — built for competitors who refuse to blend in.',
    logo: '/repulse.jpg',
    link: 'https://www.repulseco.com/',
  },
  {
    name: 'Ink3D',
    category: '3D Printed Designs',
    tier: 'Official',
    desc: 'The leading 3D design shop in esports. Ink3D brings your team\'s vision to life — custom logos, apparel, accessories, and collectibles crafted with precision for orgs, streamers, and fans who refuse to blend in.',
    logo: '/Ink3d.png',
    link: 'https://ink3dshop.com/',
  },
  {
    name: 'SCL',
    category: 'Esports League',
    tier: 'Official',
    desc: 'SCL is a competitive esports league giving players the stage to prove themselves. Overtake is proud to partner with SCL and represent our players at the highest level of organized competition.',
    logo: '/scl.png',
    link: 'https://scl.gg/',
  },
]

export const news = [
  {
    id: 19,
    title: 'OVERTAKE WELCOMES NEW ESPORTS DIRECTOR',
    date: 'July 20, 2026',
    category: 'STAFF',
    excerpt: 'Isaac officially joins Overtake as Esports Director, bringing leadership and vision to help drive the organization to the next level.',
    link: 'https://x.com/OvertakeSector/status/2079280178266558556?s=20',
    image: '/news-isaac.jpg',
  },
  {
    id: 18,
    title: 'OVERTAKE INTRODUCES NEW CHALLENGERS PLAYER',
    date: 'July 19, 2026',
    category: 'PLAYER',
    excerpt: 'T7vin officially joins Overtake as the newest CoD Challengers player, bringing competitive firepower to the academy roster.',
    link: 'https://x.com/OvertakeSector/status/2078917792774898021?s=20',
    image: '/news-t7vin.jpg',
  },
  {
    id: 17,
    title: 'OVERTAKE WELCOMES NEW CONTENT LEAD',
    date: 'July 17, 2026',
    category: 'CONTENT',
    excerpt: 'Kvstr joins Overtake as the organization\'s newest Content Lead, stepping in to shape and drive the creative direction of the brand.',
    link: 'https://x.com/OvertakeSector/status/2078223215370162334?s=20',
    image: '/news-kvstr.jpg',
  },
  {
    id: 16,
    title: 'OVERTAKE WELCOMES NEW OWNER',
    date: 'July 14, 2026',
    category: 'PARTNERSHIP',
    excerpt: 'Overtake officially welcomes Shady to Overtake, Joining forces as the THIRD owner of the Organization!',
    link: 'https://x.com/OvertakeSector/status/2077186381168902188?s=20',
    image: '/SHADY.png',
  },
  {
    id: 13,
    title: 'OVERTAKE PARTNERS WITH INK3D',
    date: 'June 24, 2026',
    category: 'PARTNERSHIP',
    excerpt: 'Overtake officially joins forces with Ink3D Studio, a premier 3D design shop bringing custom logos, apparel, and collectibles to the Overtake brand.',
    link: 'https://x.com/OvertakeSector/status/2069903396019277912?s=20',
    image: '/ink3dpartner.jpg',
  },
  {
    id: 14,
    title: 'OVERTAKE PARTNERS WITH REPULSECO',
    date: 'June 24, 2026',
    category: 'PARTNERSHIP',
    excerpt: 'Overtake proudly announces its official partnership with RepulseCo, an apparel brand redefining esports fashion for competitors who refuse to blend in.',
    link: 'https://x.com/OvertakeSector/status/2069848027066519908?s=20',
    image: '/repulseco-partner.jpg',
  },
  {
    id: 15,
    title: 'OVERTAKE ANNOUNCES NEW JERSEY LINE',
    date: 'June 24, 2026',
    category: 'MERCH',
    excerpt: 'Overtake drops its official 2026 jersey line — custom polos now available at overtakegg.com/store. Rep the org in style with personalized name and number.',
    link: 'https://x.com/OvertakeSector/status/2069858096764330021?s=20',
    image: '/jersey-announcement.jpg',
  },
  {
    id: 1,
    title: 'OVERTAKE ACQUIRES NEW VALORANT TEAM',
    date: 'June 5, 2026',
    category: 'VALORANT',
    excerpt: 'Overtake expands its roster with the acquisition of a brand new Valorant team — CFAX, SAMBAE, BLESS, SIDEBERIA, and BAZE — ready to compete at the highest level.',
    link: 'https://x.com/OvertakeSector/status/2063004328445792649?s=20',
    image: '/news-valorant.png',
  },
  {
    id: 2,
    title: 'OVERTAKE PICKS UP NEW DEADLOCK TEAM',
    date: 'June 5, 2026',
    category: 'DEADLOCK',
    excerpt: 'Overtake enters the Deadlock scene with Sheep, vCipher, E-in, KiingKooopa, Delinquent, and Maxx ready to dominate the competition.',
    link: 'https://x.com/OvertakeSector/status/2062960141306085646?s=20',
    image: '/news-deadlock.png',
  },
  {
    id: 4,
    title: 'OVERTAKE HAS A NEW ACADEMY TEAM',
    date: 'May 24, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake launches its Call of Duty Academy roster — Ghost, HoldMyPollo, Chef, and Auzkki — developing the next generation of competitive talent.',
    link: 'https://x.com/OvertakeSector/status/2058581287791894651?s=20',
    image: '/news-codacademy.png',
  },
  {
    id: 5,
    title: "OVERTAKE'S NEW FEMALE ROSTER",
    date: 'May 19, 2026',
    category: 'RAINBOW 6',
    excerpt: "Overtake proudly announces its Rainbow Six Siege female roster competing in the Aura Global Series Women's League: Cierra, Lilly, Mimi, Laken, JagerClutch, Athena, and Ghuud.",
    link: 'https://x.com/OvertakeSector/status/2056797030614172089?s=20',
    image: '/news-r6female.png',
  },
  {
    id: 9,
    title: 'OVERTAKE WINS DENVER LAN',
    date: 'April 5, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake takes home the trophy at the Denver LAN, proving dominance in competitive Call of Duty on the big stage.',
    link: 'https://x.com/OvertakeSector/status/2041028971186516153?s=20',
    image: '/news-denver.png',
  },
  {
    id: 10,
    title: 'OVERTAKE WINS VINTAGE SOCAL LAN',
    date: 'March 30, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake dominates the Vintage SoCal LAN tournament, cementing their reputation as one of the top CoD teams in the region.',
    link: 'https://x.com/OvertakeSector/status/2038578890751558141/photo/1',
    image: '/news-socal.png',
  },
  {
    id: 11,
    title: 'OVERTAKE MAKES RAINBOW 6 CHALLENGER SERIES',
    date: 'March 1, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake qualifies for the NAL Challengers Series with Lunar, Sneky, Valen, Tweedy, and Ayex leading the charge.',
    link: 'https://x.com/OvertakeSector/status/2028306360925138995?s=20',
    image: '/news-nal.png',
  },
  {
    id: 12,
    title: 'OVERTAKE ARE DIVINECORP PROVING GROUNDS CHAMPS',
    date: 'January 18, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake claims the DivineCorp Proving Grounds championship with Valen, Ayex, Tweedy, Sneky, Lunar, and Enoa.',
    link: 'https://x.com/OvertakeSector/status/2013103219547779326?s=20',
    image: '/news-divinecorp.png',
  },
]
