export const teams = [
  {
    id: 'valorant',
    game: 'VALORANT',
    tag: 'OT',
    color: '#FF4655',
    region: 'NA',
    roster: [
      { name: 'CFAX', role: 'PLAYER', country: '🇺🇸', real: 'CFAX', age: 0 },
      { name: 'SAMBAE', role: 'PLAYER', country: '🇺🇸', real: 'SAMBAE', age: 0 },
      { name: 'BLESS', role: 'PLAYER', country: '🇺🇸', real: 'BLESS', age: 0 },
      { name: 'SIDEBERIA', role: 'PLAYER', country: '🇺🇸', real: 'SIDEBERIA', age: 0 },
      { name: 'BAZE', role: 'PLAYER', country: '🇺🇸', real: 'BAZE', age: 0 },
    ],
  },
  {
    id: 'counterstrike',
    game: 'COUNTER-STRIKE',
    tag: 'OT',
    color: '#F0A500',
    region: 'NA',
    roster: [
      { name: 'UMAR', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'INTRAA', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'LEARSI', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'JASON', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'SACRIFICE', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'r6-main',
    game: 'RAINBOW 6 — MAIN',
    tag: 'OT',
    color: '#009BDE',
    region: 'NA',
    roster: [
      { name: 'SNEKY', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'BRADY', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TEAK', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'ZMAN', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'HEKTIK', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'r6-FEMALE',
    game: 'RAINBOW 6 — FEMALE',
    tag: 'OT',
    color: '#00A8E0',
    region: 'NA',
    roster: [
      { name: 'CIERRA', role: 'PLAYER', country: '🇺🇸', real: 'CIERRA', age: 0 },
      { name: 'LILLY', role: 'PLAYER', country: '🇺🇸', real: 'LILLY', age: 0 },
      { name: 'OLIVIA', role: 'PLAYER', country: '🇺🇸', real: 'OLIVIA', age: 0 },
      { name: 'MIMI', role: 'PLAYER', country: '🇺🇸', real: 'MIMI', age: 0 },
      { name: 'LAKEN', role: 'PLAYER', country: '🇺🇸', real: 'LAKEN', age: 0 },
      { name: 'JAGERCLUTCH', role: 'SUB', country: '🇺🇸', real: 'JAGERCLUTCH', age: 0 },
      { name: 'ATHENA', role: 'SUB', country: '🇺🇸', real: 'ATHENA', age: 0 },
      { name: 'GHUUD', role: 'COACH', country: '🇺🇸', real: 'GHUUD', age: 0 },
    ],
  },
  {
    id: 'iracing',
    game: 'iRACING',
    tag: 'OT',
    color: '#00C853',
    region: 'NA',
    roster: [
      { name: 'FASTNAUGHT', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'FUSION', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
      { name: 'TBA', role: 'Driver', country: '🇺🇸', real: 'Coming Soon', age: 0 },
    ],
  },
  {
    id: 'clashroyale',
    game: 'CLASH ROYALE',
    tag: 'OT',
    color: '#A855F7',
    region: 'NA',
    roster: [
      { name: 'MEGAHITIDEE', role: 'Player', country: '🇺🇸', real: 'MegaHitIdee', age: 0 },
    ],
  },
  {
    id: 'cod',
    game: 'CALL OF DUTY',
    tag: 'OT',
    color: '#00A878',
    region: 'NA',
    roster: [
      { name: 'GHOST', role: 'PLAYER', country: '🇺🇸', real: 'GHOST', age: 0 },
      { name: 'HOLDMYPOLLO', role: 'PLAYER', country: '🇺🇸', real: 'HoldMyPollo', age: 0 },
      { name: 'CHEF', role: 'PLAYER', country: '🇺🇸', real: 'CHEF', age: 0 },
      { name: 'AUZKKI', role: 'PLAYER', country: '🇺🇸', real: 'AUZKKI', age: 0 },
    ],
  },
  {
    id: 'deadlock',
    game: 'DEADLOCK',
    tag: 'OT',
    color: '#E8191A',
    region: 'NA',
    roster: [
      { name: 'SHEEP', role: 'Player', country: '🇺🇸', real: 'Sheep', age: 0 },
      { name: 'VCIPHER', role: 'Player', country: '🇺🇸', real: 'vCipher', age: 0 },
      { name: 'E-IN', role: 'Player', country: '🇺🇸', real: 'E-in', age: 0 },
      { name: 'KIINGKOOOPA', role: 'Player', country: '🇺🇸', real: 'KiingKooopa', age: 0 },
      { name: 'DELINQUENT', role: 'Player', country: '🇺🇸', real: 'Delinquent', age: 0 },
      { name: 'MAXX', role: 'Player', country: '🇺🇸', real: 'Maxx', age: 0 },
    ],
  },
]

export const creators = [
  {
    id: 'creator1',
    handle: 'TBA',
    real: 'Coming Soon',
    platform: 'Twitch',
    followers: 'TBA',
    content: 'Coming Soon',
    country: '🇺🇸',
    specialty: 'TBA',
    bio: 'Creator details coming soon.',
    socials: { twitch: '', twitter: '', youtube: '' },
  },
]

export const partners = [
  {
    name: 'RepulseCo',
    category: 'Apparel',
    tier: 'Official',
    desc: 'The fear of being normal. RepulseCo is redefining the future of esports clothing — built for competitors who refuse to blend in.',
    logo: '/repulse.jpg',
    link: 'https://www.repulseco.com/',
  },
]

export const news = [
  {
    id: 1,
    title: 'OVERTAKE ACQUIRES NEW VALORANT TEAM',
    date: 'June 5, 2026',
    category: 'VALORANT',
    excerpt: 'Overtake expands its roster with the acquisition of a brand new Valorant team — CFAX, SAMBAE, BLESS, SIDEBERIA, and BAZE — ready to compete at the highest level.',
    link: 'https://x.com/OvertakeSector/status/2063004328445792649?s=20',
    image: '/news-valorant.png',
  },
  {
    id: 2,
    title: 'OVERTAKE PICKS UP NEW DEADLOCK TEAM',
    date: 'June 5, 2026',
    category: 'DEADLOCK',
    excerpt: 'Overtake enters the Deadlock scene with Sheep, vCipher, E-in, KiingKooopa, Delinquent, and Maxx ready to dominate the competition.',
    link: 'https://x.com/OvertakeSector/status/2062960141306085646?s=20',
    image: '/news-deadlock.png',
  },
  {
    id: 3,
    title: 'OVERTAKE ENTERS CLASH ROYALE',
    date: 'May 30, 2026',
    category: 'CLASH ROYALE',
    excerpt: 'Overtake makes its mark in Clash Royale with the signing of MegaHitIdee, bringing competitive excellence to mobile esports.',
    link: 'https://x.com/OvertakeSector/status/2060738006294704365?s=20',
    image: '/news-clashroyale.png',
  },
  {
    id: 4,
    title: 'OVERTAKE HAS A NEW ACADEMY TEAM',
    date: 'May 24, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake launches its Call of Duty Academy roster — Ghost, HoldMyPollo, Chef, and Auzkki — developing the next generation of competitive talent.',
    link: 'https://x.com/OvertakeSector/status/2058581287791894651?s=20',
    image: '/news-codacademy.png',
  },
  {
    id: 5,
    title: "OVERTAKE'S NEW FEMALE ROSTER",
    date: 'May 19, 2026',
    category: 'RAINBOW 6',
    excerpt: "Overtake proudly announces its Rainbow Six Siege female roster competing in the Aura Global Series Women's League: Cierra, Lilly, Olivia, Mimi, Laken, JagerClutch, Athena, and Ghuud.",
    link: 'https://x.com/OvertakeSector/status/2056797030614172089?s=20',
    image: '/news-r6female.png',
  },
  {
    id: 9,
    title: 'OVERTAKE WINS DENVER LAN',
    date: 'April 5, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake takes home the trophy at the Denver LAN, proving dominance in competitive Call of Duty on the big stage.',
    link: 'https://x.com/OvertakeSector/status/2041028971186516153?s=20',
    image: '/news-denver.png',
  },
  {
    id: 10,
    title: 'OVERTAKE WINS VINTAGE SOCAL LAN',
    date: 'March 30, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake dominates the Vintage SoCal LAN tournament, cementing their reputation as one of the top CoD teams in the region.',
    link: 'https://x.com/OvertakeSector/status/2038578890751558141/photo/1',
    image: '/news-socal.png',
  },
  {
    id: 11,
    title: 'OVERTAKE MAKES RAINBOW 6 CHALLENGER SERIES',
    date: 'March 1, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake qualifies for the NAL Challengers Series with Lunar, Sneky, Valen, Tweedy, and Ayex leading the charge.',
    link: 'https://x.com/OvertakeSector/status/2028306360925138995?s=20',
    image: '/news-nal.png',
  },
  {
    id: 12,
    title: 'OVERTAKE ARE DIVINECORP PROVING GROUNDS CHAMPS',
    date: 'January 18, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake claims the DivineCorp Proving Grounds championship with Valen, Ayex, Tweedy, Sneky, Lunar, and Enoa.',
    link: 'https://x.com/OvertakeSector/status/2013103219547779326?s=20',
    image: '/news-divinecorp.png',
  },
]
