export const teams = [
  {
    id: 'valorant',
    game: 'VALORANT',
    tag: 'OT',
    color: '#FF4655',
    region: 'NA',
    roster: [
      { name: 'CFAX', role: 'PLAYER', country: '🇺🇸', real: '@CfaxFTW', twitter: 'https://x.com/CfaxFTW' },
      { name: 'SAMBAE', role: 'PLAYER', country: '🇺🇸', real: '@sambaeFPS', twitter: 'https://x.com/sambaeFPS' },
      { name: 'BLESS', role: 'PLAYER', country: '🇺🇸', real: '@toniorobinson7', twitter: 'https://x.com/toniorobinson7' },
      { name: 'SIDEBERIA', role: 'PLAYER', country: '🇺🇸', real: '@sideberia', twitter: 'https://x.com/sideberia' },
      { name: 'BAZE', role: 'PLAYER', country: '🇺🇸', real: '@baze_gg', twitter: 'https://x.com/baze_gg' },
    ],
  },
  {
    id: 'counterstrike',
    game: 'COUNTER-STRIKE',
    tag: 'OT',
    color: '#F0A500',
    region: 'NA',
    roster: [
      { name: 'UMAR', role: 'PLAYER', country: '🇺🇸', real: '@UmarQaiser2', twitter: 'https://x.com/UmarQaiser2' },
      { name: 'INTRAA', role: 'PLAYER', country: '🇺🇸', real: '@intrraa', twitter: 'https://x.com/intrraa' },
      { name: 'LEARSI', role: 'PLAYER', country: '🇺🇸', real: '@learsifarm', twitter: 'https://x.com/learsifarm' },
      { name: 'JASON', role: 'PLAYER', country: '🇺🇸', real: '@305jasonn', twitter: 'https://x.com/305jasonn' },
      { name: 'SACRIFICE', role: 'PLAYER', country: '🇺🇸', real: '@sacrificeCS', twitter: 'https://x.com/sacrificeCS' },
    ],
  },
  {
    id: 'deadlock',
    game: 'DEADLOCK',
    tag: 'OT',
    color: '#E8191A',
    region: 'NA',
    roster: [
      { name: 'SHEEP', role: 'PLAYER', country: '🇺🇸', real: '@SheepDL', twitter: 'https://x.com/SheepDL' },
      { name: 'VCIPHER', role: 'PLAYER', country: '🇺🇸', real: 'vCipher', twitter: '' },
      { name: 'E-IN', role: 'PLAYER', country: '🇺🇸', real: 'E-in', twitter: '' },
      { name: 'KIINGKOOOPA', role: 'PLAYER', country: '🇺🇸', real: '@KiiingKooopa', twitter: 'https://x.com/KiiingKooopa' },
      { name: 'DELINQUENT', role: 'PLAYER', country: '🇺🇸', real: '@delinquentFps', twitter: 'https://x.com/delinquentFps' },
      { name: 'MAXX', role: 'PLAYER', country: '🇺🇸', real: '@MaxxTF2', twitter: 'https://x.com/MaxxTF2' },
    ],
  },
  {
    id: 'warzone',
    game: 'WARZONE',
    tag: 'OT',
    color: '#FF6B00',
    region: 'NA',
    roster: [
      { name: 'DEASELLS', role: 'PLAYER', country: '🇺🇸', real: '@deasells', twitter: 'https://x.com/deasells' },
      { name: 'FAVOR8', role: 'PLAYER', country: '🇺🇸', real: '@Favor8_', twitter: 'https://x.com/Favor8_' },
      { name: 'GODCOOKIE', role: 'PLAYER', country: '🇺🇸', real: '@godcookie_2', twitter: 'https://x.com/godcookie_2' },
      { name: 'KONTROL', role: 'PLAYER', country: '🇺🇸', real: '@SynKontrol', twitter: 'https://x.com/SynKontrol' },
      { name: 'DANNY', role: 'PLAYER', country: '🇺🇸', real: '@Dannyvsu', twitter: 'https://x.com/Dannyvsu' },
      { name: 'XIMMY', role: 'PLAYER', country: '🇺🇸', real: '@ximmywz', twitter: 'https://x.com/ximmywz' },
      { name: 'LUKA', role: 'PLAYER', country: '🇺🇸', real: '@xLuka_77', twitter: 'https://x.com/xLuka_77' },
      { name: 'ADLIBB', role: 'PLAYER', country: '🇺🇸', real: '@libFPS', twitter: 'https://x.com/libFPS' },
    ],
  },
  {
    id: 'r6-main',
    game: 'RAINBOW 6 — MAIN',
    tag: 'OT',
    color: '#009BDE',
    region: 'NA',
    roster: [
      { name: 'SNEKY', role: 'PLAYER', country: '🇺🇸', real: '@SnekyFPS', twitter: 'https://x.com/SnekyFPS' },
      { name: 'BRADY', role: 'PLAYER', country: '🇺🇸', real: '@braydenvalen', twitter: 'https://x.com/braydenvalen' },
      { name: 'TEAK', role: 'PLAYER', country: '🇺🇸', real: '@TeakR6', twitter: 'https://x.com/TeakR6' },
      { name: 'ZMAN', role: 'PLAYER', country: '🇺🇸', real: '@ZmanFPS', twitter: 'https://x.com/ZmanFPS' },
      { name: 'HEKTIK', role: 'PLAYER', country: '🇺🇸', real: '@ripHektik', twitter: 'https://x.com/ripHektik' },
    ],
  },
  {
    id: 'r6-academy',
    game: 'RAINBOW 6 — ACADEMY',
    tag: 'OT',
    color: '#0077B6',
    region: 'NA',
    roster: [
      { name: 'KEO', role: 'PLAYER', country: '🇺🇸', real: '@keo197', twitter: 'https://x.com/keo197' },
      { name: 'SHAA', role: 'PLAYER', country: '🇺🇸', real: '@ShaaSmh', twitter: 'https://x.com/ShaaSmh' },
      { name: 'TBA', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', twitter: '' },
      { name: 'TBA', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', twitter: '' },
      { name: 'TBA', role: 'PLAYER', country: '🇺🇸', real: 'Coming Soon', twitter: '' },
    ],
  },
  {
    id: 'r6-FEMALE',
    game: 'RAINBOW 6 — FEMALE',
    tag: 'OT',
    color: '#FF69B4',
    region: 'NA',
    roster: [
      { name: 'CIERRA', role: 'PLAYER', country: '🇺🇸', real: '@nottCierra', twitter: 'https://x.com/nottCierra' },
      { name: 'LILLY', role: 'PLAYER', country: '🇺🇸', real: '@LILLY0NNA', twitter: 'https://x.com/LILLY0NNA' },
      { name: 'MIMI', role: 'PLAYER', country: '🇺🇸', real: '@mimiixoo_', twitter: 'https://x.com/mimiixoo_' },
      { name: 'LAKEN', role: 'PLAYER', country: '🇺🇸', real: '@BroSheGood', twitter: 'https://x.com/BroSheGood' },
      { name: 'JAGERCLUTCH', role: 'SUB', country: '🇺🇸', real: '@JagerClutch', twitter: 'https://x.com/JagerClutch' },
      { name: 'ATHENA', role: 'SUB', country: '🇺🇸', real: '@AthenasEgo', twitter: 'https://x.com/AthenasEgo' },
      { name: 'GHUUD', role: 'COACH', country: '🇺🇸', real: '@Ghuud_', twitter: 'https://x.com/Ghuud_', color: '#E8191A' },
    ],
  },
  {
    id: 'cod',
    game: 'CALL OF DUTY ACADEMY',
    tag: 'OT',
    color: '#00A878',
    region: 'NA',
    roster: [
      { name: 'GHOST', role: 'PLAYER', country: '🇺🇸', real: 'GHOST', twitter: '' },
      { name: 'HOLDMYPOLLO', role: 'PLAYER', country: '🇺🇸', real: 'HoldMyPollo', twitter: '' },
      { name: 'CHEF', role: 'PLAYER', country: '🇺🇸', real: 'CHEF', twitter: '' },
      { name: 'AUZKKI', role: 'PLAYER', country: '🇺🇸', real: 'AUZKKI', twitter: '' },
    ],
  },
  {
    id: 'clashroyale',
    game: 'CLASH ROYALE',
    tag: 'OT',
    color: '#A855F7',
    region: 'NA',
    roster: [
      { name: 'MEGAHITIDEE', role: 'PLAYER', country: '🇺🇸', real: '@MegaHitIDEE', twitter: 'https://x.com/MegaHitIDEE' },
    ],
  },
  {
    id: 'iracing',
    game: 'iRACING',
    tag: 'OT',
    color: '#00C853',
    region: 'NA',
    roster: [
      { name: 'FASTNAUGHT', role: 'Driver', country: '🇺🇸', real: '@MFastnaught', twitter: 'https://x.com/MFastnaught' },
      { name: 'FUSION', role: 'Driver', country: '🇺🇸', real: '@FusionRacing24', twitter: 'https://x.com/FusionRacing24' },
    ],
  },
]

export const creators = [
  {
    id: 'x19',
    handle: 'X19',
    real: 'X19_EH',
    platform: 'Twitch',
    followers: '800',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    bio: 'The gamer dad who never misses. X19 brings raw energy, unfiltered fun, and a community that feels like family — every stream, every time.',
    link: 'https://www.twitch.tv/x19_eh',
    photo: 'creatorr-x19.jpg',
    socials: { twitch: 'x19_eh', twitter: 'https://x.com/X19_EH', youtube: '' },
  },
  {
    id: 'luke',
    handle: 'LUKE',
    real: 'LukeFrywalker24',
    platform: 'Twitch',
    followers: '100',
    content: 'Gaming',
    country: '🇺🇸',
    specialty: 'VARIETY GAMING',
    bio: 'Luke Frywalker is cooking up content one stream at a time. Fresh takes, good games, and a growing presence across Twitch and YouTube.',
    link: 'https://www.twitch.tv/luke_12345678932',
    photo: 'creator-Luke.jpg',
    socials: { twitch: 'luke_12345678932', twitter: 'https://x.com/LukeFrywalker24', youtube: '' },
  },
  {
    id: 'zendigo',
    handle: 'ZENDIGO',
    real: 'ZendigoPlayz',
    platform: 'Twitch',
    followers: '200',
    content: 'Speedrunning',
    country: '🇺🇸',
    specialty: 'SPEEDRUNS & RETRO',
    bio: 'Retro games, hidden gems, and speedruns that defy belief. Zendigo is on a mission to make the old feel new again — and the fast feel faster.',
    link: 'https://www.twitch.tv/zendigo_playz',
    photo: 'creator-Zendigo.jpg',
    socials: { twitch: 'zendigo_playz', twitter: 'https://x.com/ZendigoPlayz', youtube: '' },
  },
  {
    id: 'oficr',
    handle: 'OFICR',
    real: 'OfficialOFICR',
    platform: 'Twitch',
    followers: '4.8K',
    content: 'Marvel Rivals',
    country: '🇺🇸',
    specialty: 'MARVEL RIVALS',
    bio: 'Gamer, nerd, father, and one of the most interactive streamers on Twitch. OFICR\'s channel isn\'t just a stream — it\'s a community where everyone belongs.',
    link: 'https://www.twitch.tv/oficr',
    photo: 'creator-Oficr.jpg',
    socials: { twitch: 'oficr', twitter: 'https://x.com/OfficialOFICR', youtube: '' },
  },
  {
    id: 'lordrogue',
    handle: 'LORDROGUE',
    real: 'LordRogue22',
    platform: 'Twitch',
    followers: '500',
    content: 'IRL & Apex',
    country: '🇺🇸',
    specialty: 'IRL & APEX',
    bio: 'Five years in the game and still going strong. Lord Rogue keeps it real — competitive Apex, genuine convos, and the foundation of his own rising empire, the Rogue Army.',
    link: 'https://www.twitch.tv/lordrogue22',
    photo: 'creator-Lordrogue.jpg',
    socials: { twitch: 'lordrogue22', twitter: 'https://x.com/LordRogue22', youtube: '' },
  },
  {
    id: 'depmonk',
    handle: 'DEPMONK',
    real: 'Gtiansd',
    platform: 'Twitch',
    followers: '150',
    content: 'Fortnite',
    country: '🇺🇸',
    specialty: 'FORTNITE',
    bio: 'One day video games will reign supreme — and Depmonk plans to be there when they do. Grinding Fortnite and building something bigger, one stream at a time.',
    link: 'https://www.twitch.tv/depmonk',
    photo: 'creator-Depmonk.jpg',
    socials: { twitch: 'depmonk', twitter: 'https://x.com/Gtiansd', youtube: '' },
  },
]

export const partners = [
  {
    name: 'RepulseCo',
    category: 'Apparel',
    tier: 'Official',
    desc: 'The fear of being normal. RepulseCo is redefining the future of esports clothing — built for competitors who refuse to blend in.',
    logo: '/repulse.jpg',
    link: 'https://www.repulseco.com/',
  },
]

export const news = [
  {
    id: 1,
    title: 'OVERTAKE ACQUIRES NEW VALORANT TEAM',
    date: 'June 5, 2026',
    category: 'VALORANT',
    excerpt: 'Overtake expands its roster with the acquisition of a brand new Valorant team — CFAX, SAMBAE, BLESS, SIDEBERIA, and BAZE — ready to compete at the highest level.',
    link: 'https://x.com/OvertakeSector/status/2063004328445792649?s=20',
    image: '/news-valorant.png',
  },
  {
    id: 2,
    title: 'OVERTAKE PICKS UP NEW DEADLOCK TEAM',
    date: 'June 5, 2026',
    category: 'DEADLOCK',
    excerpt: 'Overtake enters the Deadlock scene with Sheep, vCipher, E-in, KiingKooopa, Delinquent, and Maxx ready to dominate the competition.',
    link: 'https://x.com/OvertakeSector/status/2062960141306085646?s=20',
    image: '/news-deadlock.png',
  },
  {
    id: 3,
    title: 'OVERTAKE ENTERS CLASH ROYALE',
    date: 'May 30, 2026',
    category: 'CLASH ROYALE',
    excerpt: 'Overtake makes its mark in Clash Royale with the signing of MegaHitIdee, bringing competitive excellence to mobile esports.',
    link: 'https://x.com/OvertakeSector/status/2060738006294704365?s=20',
    image: '/news-clashroyale.png',
  },
  {
    id: 4,
    title: 'OVERTAKE HAS A NEW ACADEMY TEAM',
    date: 'May 24, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake launches its Call of Duty Academy roster — Ghost, HoldMyPollo, Chef, and Auzkki — developing the next generation of competitive talent.',
    link: 'https://x.com/OvertakeSector/status/2058581287791894651?s=20',
    image: '/news-codacademy.png',
  },
  {
    id: 5,
    title: "OVERTAKE'S NEW FEMALE ROSTER",
    date: 'May 19, 2026',
    category: 'RAINBOW 6',
    excerpt: "Overtake proudly announces its Rainbow Six Siege female roster competing in the Aura Global Series Women's League: Cierra, Lilly, Mimi, Laken, JagerClutch, Athena, and Ghuud.",
    link: 'https://x.com/OvertakeSector/status/2056797030614172089?s=20',
    image: '/news-r6female.png',
  },
  {
    id: 9,
    title: 'OVERTAKE WINS DENVER LAN',
    date: 'April 5, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake takes home the trophy at the Denver LAN, proving dominance in competitive Call of Duty on the big stage.',
    link: 'https://x.com/OvertakeSector/status/2041028971186516153?s=20',
    image: '/news-denver.png',
  },
  {
    id: 10,
    title: 'OVERTAKE WINS VINTAGE SOCAL LAN',
    date: 'March 30, 2026',
    category: 'BLACK OPS 7',
    excerpt: 'Overtake dominates the Vintage SoCal LAN tournament, cementing their reputation as one of the top CoD teams in the region.',
    link: 'https://x.com/OvertakeSector/status/2038578890751558141/photo/1',
    image: '/news-socal.png',
  },
  {
    id: 11,
    title: 'OVERTAKE MAKES RAINBOW 6 CHALLENGER SERIES',
    date: 'March 1, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake qualifies for the NAL Challengers Series with Lunar, Sneky, Valen, Tweedy, and Ayex leading the charge.',
    link: 'https://x.com/OvertakeSector/status/2028306360925138995?s=20',
    image: '/news-nal.png',
  },
  {
    id: 12,
    title: 'OVERTAKE ARE DIVINECORP PROVING GROUNDS CHAMPS',
    date: 'January 18, 2026',
    category: 'RAINBOW 6',
    excerpt: 'Overtake claims the DivineCorp Proving Grounds championship with Valen, Ayex, Tweedy, Sneky, Lunar, and Enoa.',
    link: 'https://x.com/OvertakeSector/status/2013103219547779326?s=20',
    image: '/news-divinecorp.png',
  },
]
